### Post request to create new patient
POST http://localhost:4000/patient/add-patient
Content-Type: application/json

{
    "name":"whatever",
    "email":"whatever10@exma.com",
    "phone":"123123123",
    "address":"jordan",
    "birthDate":"1948-12-03",
    "registrationDate":"1948-12-03"
}

###